### ISSUE TITLE
Voice tin traffic sometimes delayed by more than one bulk packet in best effort.

### ISSUE THREAD

**Issue by AndyFurniss** [dtaht/sch_cake#52] opened 2017-03-05 12:32 UTC
Mailing list discussion
https://lists.bufferbloat.net/pipermail/cake/2017-March/002508.html

In summary sending sparse traffic to voice while there is bulk in best effort can result in worse delay than sending all through best effort.

**Comment by ldir-EDB0** [comment] 2017-03-08 13:21
Is this as 'simple' as always starting at the highest priority tin (rather than the last active tin) and working through to the lowest?

https://github.com/dtaht/sch_cake/blob/master/sch_cake.c#L1097

https://github.com/dtaht/sch_cake/blob/master/sch_cake.c#L1123

**Comment by chromi** [comment] 2017-03-08 19:48
> On 8 Mar, 2017, at 15:21, Kevin Darbyshire-Bryant <notifications@github.com> wrote:
> 
> Is this as 'simple' as always starting at the highest priority tin (rather than the last active tin) and working through to the lowest?

If that was the only change I made, it would mess up the balancing mechanism, and allow the top tins to exceed their allocated bandwidth even under contention.  At minimum, I would need to delay replenishing the tin deficits until all tins were exhausted (of deficit or traffic), which I suspect would make delivery just as “lumpy” as it is now.

I have several potential solutions in mind, but I need to dedicate some serious thinking time to work out which one is best and to flesh out the details.  With any luck I can still leverage the algorithms already used in Cake, rather than inventing yet another one out of whole cloth.

 - Jonathan Morton

**Comment by chromi** [comment] 2017-03-16 21:29
Currently my thinking is to re-introduce the shaper algorithm in direct control of the priority layer, rather than just managing the threshold of the DRR as it presently does.  With a slight modification, it should be possible to prevent it from getting seriously out of step when a tin is permitted to exceed its own bandwidth due to underutilisation of other tins.

Where this is likely to fall over, however, is when using Cake in "unlimited" mode, where all the shapers currently get infinite bandwidth (that is, no time consumed per byte transmitted).  That's an edge case I still need to work out how to solve.

**Comment by chromi** [comment] 2017-04-04 11:34
Currently the "cobalt" branch has an implementation of this which appears to function, though I haven't explicitly verified the theoretical latency improvement.  I got around the "unlimited mode" problem by leaving in a copy of the DRR just for that particular case.

I'd be interested to hear how it works for you.

**Comment by AndyFurniss** [comment] 2017-04-04 23:39
Current cobalt behaves the same as master for me, so the issue persists.
I am not and haven't ever tested unlimited though.

**Comment by dtaht** [comment] 2017-12-04 05:49
?

**Comment by chromi** [comment] 2017-12-04 06:47
I wouldn't consider this one a blocker.

- Jonathan Morton

**Comment by dtaht** [comment] 2017-12-06 21:17
I don't consider it a blocker, either, but it is interesting.

**Comment by gamanakis** [comment] 2019-03-27 13:38
It has been a long time since this was reported. FWIW I cannot reproduce this behaviour using the current code with Andy's test (in the mailing list).

**Comment by chromi** [comment] 2019-03-27 13:39
In that case, is it sensible to close this one now?

 - Jonathan Morton

**Comment by tohojo** [comment] 2020-06-24 15:07
Closing this as outdated; please re-open if the issue persists...

**Closed as completed by tohojo** 2020-06-24 15:07 UTC
