### ISSUE TITLE
immediate kernel hang with cobalt branch

### ISSUE THREAD

**Issue by brettowe** [dtaht/sch_cake#54] opened 2017-03-20 22:11 UTC
recently tried updating cake to latest on kernel 4.10.4 on arch linux
and as soon as the module is put to use I get a hang on the system and have to force reset
I've checked logs and see nothing, while shelled in to physical machine terminal also hangs
didn't see full dump from when ssh'd into it but looked like it mentioned cake_dequeue
I didn't take a picture since it was not a full trace
last stable i had was from 15 days ago

at this time testing for fixes will be delayed a day or 2

**Comment by chromi** [comment] 2017-03-20 22:14
> On 21 Mar, 2017, at 00:11, brettowe <notifications@github.com> wrote:
> 
> didn't see full dump from when ssh'd into it but looked like it mentioned cake_dequeue

I did have a bug like that a little while ago, but it should be fixed now.  Does ‘git pull’ bring anything new in?

 - Jonathan Morton

**Comment by brettowe** [comment] 2017-03-20 22:22
nope nothing new pulled, and ill note the log message i saw matched what i saw on web ui here on github

**Comment by chromi** [comment] 2017-03-20 22:26
> On 21 Mar, 2017, at 00:22, brettowe <notifications@github.com> wrote:
> 
> nope nothing new pulled, and ill note the log message i saw matched what i saw on web ui here on github

I see.  For now, please use the ‘master’ branch; ‘cobalt’ is what I use for experiments.  The current code is in fact working for me, but I may need to investigate more closely.

To help me investigate, what configuration keywords are you using?

 - Jonathan Morton

**Comment by brettowe** [comment] 2017-03-20 22:35
the only command that was used to cause the crash was this one
tc qdisc add dev wan0 root handle 1:0 cake bandwidth 648kbit rtt 110ms besteffort flowblind raw

ill switch back to master in a couple days and try that then and test out anything you want tested out at that time also

**Comment by chromi** [comment] 2017-04-04 11:32
I've been completely unable to reproduce this one.  Can you try again with the latest commit to make sure it wasn't a fluke?

**Comment by brettowe** [comment] 2017-04-04 16:37
trashed the directory completely re-pulled cobalt branch after reboot into new kernel 4.10.8 make install and ran the line i provided earlier and dead server again
nothing in logs

**Comment by chromi** [comment] 2017-04-04 16:50
> On 4 Apr, 2017, at 19:37, brettowe <notifications@github.com> wrote:
> 
> trashed the directory completely re-pulled cobalt branch after reboot into new kernel 4.10.8 make install and ran the line i provided earlier and dead server again

That’s definitely weird.  Can I have your kernel config?  Is it AMD64 or some other platform?

 - Jonathan Morton

**Comment by brettowe** [comment] 2017-04-04 20:06
its just testing version of normal linux version in arch linux
testing/linux 4.10.8-1 (base) [installed]
so not a special config
hardware is amd64
model name	: Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
and intel chipset on the ethernet side
01:00.0 Ethernet controller: Intel Corporation 82571EB Gigabit Ethernet Controller (rev 06)

i can attach the config if needed tho

**Comment by chromi** [comment] 2017-04-04 21:03
> On 4 Apr, 2017, at 23:06, brettowe <notifications@github.com> wrote:
> 
> i can attach the config if needed tho

Please do.  If I can reproduce the problem with a vanilla kernel, rather than a vendor-patched one, it’ll be that much easier to fix.  Also, a config file is much smaller and more convenient to work with than a complete distro.

I have only AMD hardware to work with at the moment, but that theoretically shouldn’t be a problem.

 - Jonathan Morton

**Comment by brettowe** [comment] 2017-04-04 21:26
[config.gz](https://github.com/dtaht/sch_cake/files/894587/config.gz)

**Comment by chromi** [comment] 2017-04-05 07:58
I built vanilla 4.10.8 with that config, and since it's extremely modular (as distro kernel builds often are), I had to shove all the modules in an initramfs to make it boot on my E-450.

The latest cobalt branch then loaded and passed traffic without any problems, though I'm missing the IFB and mirred modules needed for my usual setup.  I was able to complete a dslreports speed test.

Can you try the same, using the vanilla kernel source rather than the Arch specific one?

**Comment by brettowe** [comment] 2017-04-05 15:26
looking here: https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/linux
at pkgbuild i see no patches added
so i question what gcc maybe?
gcc version 6.3.1 20170306 (GCC)

and ill note with arch i do have ifb working, just not loaded in the script that causes the crash

**Comment by chromi** [comment] 2017-04-05 16:18
That machine is using:  gcc version 4.9.4 (Gentoo 4.9.4 p1.0, pie-0.6.4) 

I'm a little surprised that there's such a big difference in versions, given Gentoo's nature, but they might be a little conservative on such fundamental components as the compiler and glibc.

**Comment by xnoreq** [comment] 2017-04-05 21:45
@brettowe I have just tried the cobalt branch on an up-to-date Arch system (Linux 4.10.6, gcc 6.3.1) and it works just fine.

All I did was:
Install base-devel, linux header.
Git clone cake, git checkout cobalt, make.
`sudo insmod sch_cake.ko`
Also clone and make the patched tc. 
`sudo ./tc/tc -s -d qdisc add dev <interface> root cake`

If you post exactly what you're doing I could try to reproduce your crash.

**Comment by brettowe** [comment] 2017-04-05 21:58
well thats not encouraging on my side
so commands was
 git clone -b cobalt https://github.com/dtaht/sch_cake.git
make, make install
then run the script attached
script completes for me but immediately system no longer responds to commands
 
renamed to .txt just in case github would complain
[hardware-set-cake.txt](https://github.com/dtaht/sch_cake/files/900901/hardware-set-cake.txt)

**Comment by chromi** [comment] 2017-04-05 22:07
And you're certain there's a difference here between "master" and "cobalt" branches?

**Comment by brettowe** [comment] 2017-04-05 22:09
I'm running master now without issue, last time i ran with the -b cobalt i had a dead server till i hit reset

**Comment by chromi** [comment] 2017-04-05 22:33
Okay, further troubleshooting:

Is HPET enabled in BIOS?  Does toggling it help?  (I normally run with it on.)

Any kind of virtualisation in use?

Can you get a screenshot (probably literal) of a panic/oops message, and also attach the corresponding module binary?

**Comment by brettowe** [comment] 2017-04-06 02:24
hpet ill get back to you when i can reboot the server
kernel reports using tsc at the moment
virtualization is being used so there is a bridge device which lan0 is part of
so far I've only seen the 1st event on the monitor and it wasn't even complete its like the system fully hung 1/3 of the way thru displaying it on console
didn't think to take a picture at the time
ill follow up tomorrow with bios info and module i doubt ill be able to get a panic shot

**Comment by chromi** [comment] 2017-04-06 20:22
There may have been an uninitialised pointer in some cases, which should now be fixed.  Can you try with the latest commit?

**Comment by brettowe** [comment] 2017-04-07 16:08
glad to say it is running just fine now

on a side note looks like from what I read in my case using tsc is likely a better option than hpet
higher resolution and lower load, so that's likely why kernel choose it

**Closed as completed** 2017-04-07 16:09 UTC
